import { type NextPage } from "next";
import Head from "next/head";


const SinglePostPage: NextPage = () => {

  return (
    <>
      <Head>
        <title>Chirp-Emoji</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen justify-center">
        <div className=" h-full w-full">
Profile View
        </div>
      </main>
    </>
  );
};

export default SinglePostPage;
